### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by KyGost** [CodedSakura/SetBonuses#1]
This mod looks awesome! Can't wait to try it.

Trying to start the server throws this though:
```
Caused by: java.lang.NoSuchFieldException: MAINHAND
at java.lang.Class.getField(Class.java:2086) ~[?:?]
at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:797) ~[server.jar:?]
at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:834) ~[server.jar:?]
at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48) ~[server.jar:?]
at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[server.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[server.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[server.jar:?]
at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48) ~[server.jar:?]
at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[server.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[server.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[server.jar:?]
at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[server.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[server.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[server.jar:?]
at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:886) ~[server.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:825) ~[server.jar:?]
at eu.codedsakura.setbonuses.config.ConfigReader.read(ConfigReader.java:21) ~[set-bonuses-0.1.0.jar:?]
at eu.codedsakura.setbonuses.SetBonuses.onInitialize(SetBonuses.java:19) ~[set-bonuses-0.1.0.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
... 17 more
```

**Comment by CodedSakura** [comment]
hmm, i haven't made support for non-armor enchantments, so `MAINHAND` is not a valid field anywhere.. after the gamejam results are published i'll continue work and probably will add support for weapon and tool enchantments.

**Comment by KyGost** [comment]
Curiously, I hadn't yet changed the config and yet it threw that.

**Comment by CodedSakura** [comment]
intruiging, mind sending a full crash log and the config?

**Comment by KyGost** [comment]
Apologies! I missed this message and now there is no convinient way for me to reproduce for a log.
Feel free to close.
